Add almost adequate non-java report generator #2687 Report generating process is rewritten and migrated to SAX Add bundled xml parser, bug #2612 Solve problems with java during building process, see bug #2607

diff --git a/bin/olver_pre b/bin/olver_pre
--- a/bin/olver_pre
+++ b/bin/olver_pre
@@ -43,9 +43,24 @@ fi
 
 # Perl
 if [ $check_perl -eq 0 ]; then
-    echo "$issue_count) Perl is required to build reports"
+    echo "$issue_count) Perl is required to generate reports"
     echo
     issue_count=$(( $issue_count + 1 ))
+fi
+
+# XML Parser
+if [ ! -z $OLVER_XML_PARSER ]; then
+    { perl <<SCRIPT
+use $OLVER_XML_PARSER;
+my \$parser = $OLVER_XML_PARSER->new();
+\$parser->parse({Source => {String => '<test>test</test>'}});
+SCRIPT
+} 2>/dev/null
+    if [ $? -ne 0 ]; then
+        echo "$issue_count) Warning: There is no such a perl xml parser called '$OLVER_XML_PARSER'"
+        echo
+        issue_count=$(( $issue_count + 1 ))
+    fi
 fi
 
 if [ $check_lsb -eq 0 -o $check_perl -eq 0 ]; then
