sysconf problem, bug #2699 small bug fix

diff --git a/bin/olver_report b/bin/olver_report
--- a/bin/olver_report
+++ b/bin/olver_report
@@ -72,8 +72,8 @@ fi
 
 perl <<SCRIPT
 open(RES, '$REPORT_DIR/res.xml');
-while(reverse <RES>){
-    exit 0 if(/<\/Report>/);
+while(<RES>){
+    exit 0 if(/<\/Report>/o);
 }
 close(RES);
 exit 1;
@@ -82,8 +82,22 @@ SCRIPT
 if [ $? -ne 0 ]; then
     ls $REPORT_DIR/*.ut* >/dev/null 2>&1
     if [ $? -eq 0 ]; then
-        ../tools/reportgen/report.pl -d $REPORT_DIR/report -x $REPORT_DIR/res.xml $REPORT_DIR/*.ut*
+        ../tools/reportgen/report.pl $GENOPT $REPORT_DIR/*.ut*
     fi
+fi
+
+perl <<SCRIPT
+open(RES, '$REPORT_DIR/res.xml');
+while(<RES>){
+    exit 0 if(/<\/Report>/o);
+}
+close(RES);
+exit 1;
+SCRIPT
+
+if [ $? -ne 0 ]; then
+    echo "error: Couldn't generate report"
+    exit 1
 fi
 
 #
