Resolving Bugs: 2335, 2329

diff --git a/tools/buildrpm/post b/tools/buildrpm/post
--- a/tools/buildrpm/post
+++ b/tools/buildrpm/post
@@ -1,32 +1,95 @@
+RES=0
 /opt/lsb/test/olver-core/testdata/install_testdata.sh
-chown -R olver_tester:olver /opt/lsb/test/olver-core/* >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -type d -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -type f -exec chmod 664 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core/bin -maxdepth 1 -type f ! -name 'testplan' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -name 'tjreport' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -name 'stargen' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -name '*.sh' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -name '*.pl' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -name '*.exe' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-find /opt/lsb/test/olver-core -name '*.bat' -exec chmod 775 '{}' \; >/dev/null 2>/dev/null
-chown root:root /opt/lsb/test/olver-core/bin/agent
-chmod +s /opt/lsb/test/olver-core/bin/agent
-chown olver_tester:olver /usr/share/terminfo/o/olverct >/dev/null 2>/dev/null
-chmod 775 /usr/share/terminfo/o/olverct >/dev/null 2>/dev/null
 
-ls -l /lib/ld-lsb*.3 >/dev/null 2>/dev/null
+echo "Setting permissions..."
+find /opt/lsb/test/olver-core -type d -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -type f -exec chmod 664 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core/bin -maxdepth 1 -type f ! -name 'testplan' -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -name 'tjreport' -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -name 'stargen' -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -name '*.sh' -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -name '*.pl' -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -name '*.exe' -exec chmod 775 '{}' \; >/dev/null
+find /opt/lsb/test/olver-core -name '*.bat' -exec chmod 775 '{}' \; >/dev/null
+chmod +s /opt/lsb/test/olver-core/bin/agent >/dev/null
+chmod 775 /usr/share/terminfo/o/olverct >/dev/null
+
+echo "Preparing tester account..."
+# There is a necessity to have particular group and user beforehand because
+# the files unpacked have to be owned by the correct user
+cat /etc/group | grep ^olver: > /dev/null 2>/dev/null
 if [ $? -ne 0 ]; then
-    CUR_ARCH=`uname -m`
-    echo "Warning: can't find the LSB Runtime loader as /lib/ld-lsb*.3"
-    
-    if [ -f /lib/ld-linux.so.2 ]; then
-        ln -s /lib/ld-linux.so.2 /lib/ld-lsb.so.3
-        echo "Creating symbolic link /lib/ld-lsb.so.3 for /lib/ld-linux.so.2"
-    elif [ -f /lib/ld-linux-$CUR_ARCH.so.2 ]; then
-        ln -s /lib/ld-linux-$CUR_ARCH.so.2 /lib/ld-lsb-$CUR_ARCH.so.3
-        echo "Creating symbolic link /lib/ld-lsb-$CUR_ARCH.so.3 for /lib/ld-linux-$CUR_ARCH.so.2"
-    else
-        echo "Make apropriate symbolic link for it manually"
-    fi
+	groupadd olver > /dev/null 2>/dev/null
+	if [ $? -ne 0 ]; then
+		/usr/sbin/groupadd olver > /dev/null 2>/dev/null
+	fi
+	if [ $? = 0 ]; then
+		echo "Group 'olver' was successfully added"
+	else
+		echo "Error: failed to add group 'olver'"
+		echo "Try to do it manually"
+		RES=1
+	fi
 fi
-exit 0
+
+TESTER=olver_tester
+id $TESTER > /dev/null 2>/dev/null
+if [ $? -ne 0 ]; then
+	useradd -g olver -d /home/$TESTER -s /bin/sh -c "OLVER tester login" $TESTER -m > /dev/null 2>/dev/null
+	if [ $? -ne 0 ]; then
+		/usr/sbin/useradd -g olver -d /home/$TESTER -s /bin/sh -c "OLVER tester login" $TESTER -m > /dev/null 2>/dev/null
+	fi
+	if [ $? = 0 ]; then
+		echo "User '$TESTER' was successfully added"
+	else
+		echo "Error: failed to add user '$TESTER' to the group 'olver'"
+		echo "Try to do it manually"
+		RES=1
+	fi
+else
+	if [ `id $TESTER -g -n` != "olver" ]; then
+		usermod -g olver -d /home/$TESTER -m -s /bin/sh -c "OLVER tester login" $TESTER > /dev/null 2>/dev/null
+		if [ $? -ne 0 ]; then
+			/usr/sbin/usermod -g olver -d /home/$TESTER -m -s /bin/sh -c "OLVER tester login" $TESTER > /dev/null 2>/dev/null
+		fi
+		if [ `id $TESTER -g -n` != "olver" ]; then
+			echo "Error: failed to change initial group of '$TESTER' to 'olver'"
+			echo "Try to do it manually"
+			RES=1
+		else
+			echo "Initial group of '$TESTER' was successfully changed to 'olver'"
+		fi
+	fi
+fi
+
+echo "Setting ownership..."
+id $TESTER > /dev/null 2>/dev/null
+if [ $? -ne 0 ]; then
+	echo "Error: can't change owner, user '$TESTER' doesn't exist"
+	echo "Try to add user $TESTER manually and then do:"
+	echo "chown -R $TESTER:olver /opt/lsb/test/olver-core/*"
+	echo "chown root:root /opt/lsb/test/olver-core/bin/agent"
+	echo "chown $TESTER:olver /usr/share/terminfo/o/olverct"
+	RES=1
+else
+	if [ `id $TESTER -g -n` != "olver" ]; then
+		echo "Error: can't change ownership, user '$TESTER' doesn't belong to 'olver' group"
+		echo "Try to change initial group of user $TESTER to 'olver' manually and then do:"
+		echo "chown -R $TESTER:olver /opt/lsb/test/olver-core/*"
+		echo "chown root:root /opt/lsb/test/olver-core/bin/agent"
+		echo "chown $TESTER:olver /usr/share/terminfo/o/olverct"
+		RES=1
+	else
+		chown -R $TESTER:olver /opt/lsb/test/olver-core/* >/dev/null
+		chown root:root /opt/lsb/test/olver-core/bin/agent >/dev/null
+		chown $TESTER:olver /usr/share/terminfo/o/olverct >/dev/null
+	fi
+fi
+
+if [ $RES = 0 ]; then
+	echo "Done"
+	exit 0
+else
+	echo "Failed"
+	exit 1
+fi
