build fixed

diff --git a/tools/buildrpm/post b/tools/buildrpm/post
--- a/tools/buildrpm/post
+++ b/tools/buildrpm/post
@@ -5,4 +5,20 @@ chown root:root /opt/lsb/test/olver-core/bin/agent
 chmod +s /opt/lsb/test/olver-core/bin/agent
 chown olver_tester:olver /usr/share/terminfo/o/olverct >/dev/null 2>/dev/null
 chmod 755 /usr/share/terminfo/o/olverct >/dev/null 2>/dev/null
+
+ls -l /lib/ld-lsb*.3 >/dev/null 2>/dev/null
+if [ $? -ne 0 ]; then
+    CUR_ARCH=`uname -m`
+    echo "Warning: can't find the LSB Runtime loader as /lib/ld-lsb*.3"
+    
+    if [ -f /lib/ld-linux.so.2 ]; then
+        ln -s /lib/ld-linux.so.2 /lib/ld-lsb.so.3
+        echo "Creating symbolic link /lib/ld-lsb.so.3 for /lib/ld-linux.so.2"
+    elif [ -f /lib/ld-linux-$CUR_ARCH.so.2 ]; then
+        ln -s /lib/ld-linux-$CUR_ARCH.so.2 /lib/ld-lsb-$CUR_ARCH.so.3
+        echo "Creating symbolic link /lib/ld-lsb-$CUR_ARCH.so.3 for /lib/ld-linux-$CUR_ARCH.so.2"
+    else
+        echo "Make apropriate symbolic link for it manually"
+    fi
+fi
 exit 0
