bug 2366, 2373 fixed

diff --git a/tools/buildrpm/post b/tools/buildrpm/post
--- a/tools/buildrpm/post
+++ b/tools/buildrpm/post
@@ -1,19 +1,6 @@
 RES=0
 /opt/lsb/test/olver-core/testdata/install_testdata.sh
 
-echo "Setting permissions..."
-find /opt/lsb/test/olver-core -type d -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -type f -exec chmod 664 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core/bin -maxdepth 1 -type f ! -name 'testplan' -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -name 'tjreport' -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -name 'stargen' -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -name '*.sh' -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -name '*.pl' -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -name '*.exe' -exec chmod 775 '{}' \; >/dev/null
-find /opt/lsb/test/olver-core -name '*.bat' -exec chmod 775 '{}' \; >/dev/null
-chmod +s /opt/lsb/test/olver-core/bin/agent >/dev/null
-chmod 775 /usr/share/terminfo/o/olverct >/dev/null
-
 echo "Preparing tester account..."
 # There is a necessity to have particular group and user beforehand because
 # the files unpacked have to be owned by the correct user
@@ -84,6 +71,15 @@ else
 		chown root:root /opt/lsb/test/olver-core/bin/agent >/dev/null
 		chown $TESTER:olver /usr/share/terminfo/o/olverct >/dev/null
 	fi
+fi
+
+echo "Setting permissions..."
+chmod +s /opt/lsb/test/olver-core/bin/agent >/dev/null
+if [ $? -ne 0 ]; then
+	echo "Error: can't set proper permissions"
+	echo "Try to do it manually:"
+	echo "chmod +s /opt/lsb/test/olver-core/bin/agent"
+	RES=1
 fi
 
 if [ $RES = 0 ]; then
